### ISSUE TITLE
Nodejs_image: build aborted: no such package '@nodejs//'

### ISSUE THREAD

**Issue by branks** [bazelbuild/rules_docker#2016]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule:  nodejs_image

### Is this a regression?

Not sure, but I believe so

### Description
I am using rules_nodejs-5.1.0 and rules_docker-v0.23.0 - I have followed the tips in the v5 migration guide as well and when I try to run a docker build, I get the error of 

```
Analysis of target '//my_app:docker' failed; build aborted: no such package '@nodejs//': The 
repository` '@nodejs' could not be resolved: Repository '@nodejs' is not defined
```

I have tried renaming the nodejs toolchain with `nodejs_register_toolchains` but get the same error, just referencing the new name instead of `@nodejs`

## 🔬 Minimal Reproduction
https://github.com/branks/docker_nodejs_build_fail

## 🔥 Exception or Error
```
$ bazel run //my_app:docker --define=VERBOSE_LOGS=1
INFO: Build option --define has changed, discarding analysis cache.
ERROR: /home/xxx/my_app/BUILD:10:13: no such package '@nodejs//': The repository '@nodejs' could not be resolved: Repository '@nodejs' is not defined and referenced by '//my_app:docker.1'
ERROR: Analysis of target '//my_app:docker' failed; build aborted: no such package '@nodejs//': The repository '@nodejs' could not be resolved: Repository '@nodejs' is not defined
INFO: Elapsed time: 0.412s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 223 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 223 targets configured)
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.11.0
Build label: 5.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 19 14:08:54 2022 (1642601334)
Build timestamp: 1642601334
Build timestamp as int: 1642601334
  </code>
</pre>

**Rules_docker version:**

<pre>
  <code>
    0.23.0
  </code>
</pre>

**Anything else relevant?**

**Comment by ex0ns** [comment]
I'm also having this issue, did you find a fix ? This seems related to https://github.com/bazelbuild/rules_nodejs/issues/3282 which should have been fixed in 0.23.0 of the rules_docker but it does not seem to be the case

**Comment by branks** [comment]
In my example project I have follow those steps and it still doesn't work

**Comment by ex0ns** [comment]
It's because now, even if you called `nodejs_register_toolchains` with `nodejs` as a name, it will not create a `@nodejs` repository.
See https://github.com/bazelbuild/rules_nodejs/blob/9dddd19bc9bc91cb5a0fd932e3cc2d601133a9ea/nodejs/repositories.bzl#L382

So I think that you have to specify 
```
    node_repository_name = "nodejs_host",
```
Where `nodejs` is the name you gave to `nodejs_register_toolchains` and `host` the platform you are targeting. This option is missing in your BUILD file (https://github.com/branks/docker_nodejs_build_fail/blob/master/my_app/BUILD#L14)

Hope it can solve you issue, it did for mine

**Comment by comradesharf** [comment]
@branks You should change your kwarg `node_repository_name` at  `nodejs_image` rule to the correct name e.g.  nodejs_darwin_amd64; see https://github.com/bazelbuild/rules_docker/pull/1982/files#diff-cfdb50319114368f101f2a2e4b5bc1e385e074bb8636524396761fecd3f20b56R120-R122

**Comment by branks** [comment]
I have changed the name of the toolchain in every location appropriately - see here
https://github.com/branks/docker_nodejs_build_fail/commit/2892ad22cd2eff42f2c9ccd36d3ba971524bed26

Or am I doing something wrong?

**Comment by branks** [comment]
So I mangaed to get it working when using `node_repository_name = "nodejs_linux_amd64",` on the `nodejs_image` - however is there a way to make this dynamic so it will also work on windows/mac etc? Or should I use a select statement to do this perhaps?

**Comment by branks** [comment]
Ah amazing, thanks!

**Comment by summer-ji-eng** [comment]
After update 5.1.0

I have similar issue with log https://github.com/googleapis/gapic-generator-typescript/runs/5152797005?check_suite_focus=true

and PR https://github.com/googleapis/gapic-generator-typescript/pull/1111/files
