### ISSUE TITLE
rules_docker broken on Bazel's downstream projects

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/rules_docker#601]
rules_docker tests don't work with Bazel HEAD, probably because --incompatible_strict_action_env has been flipped to true. Some tests fail because the `bazel` command is not on the PATH.
```
+++ bazel test --test_output=all //test_folder:test_for_failure
++ out='/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5b031cc74a6f71160756712e3d8d076d/sandbox/linux-sandbox/568/execroot/io_bazel_rules_docker/bazel-out/k8-fastbuild/bin/tests/contrib/test_compare_ids_test_diff_ids_fails.runfiles/io_bazel_rules_docker/tests/contrib/test_compare_ids_test_diff_ids_fails: line 73: bazel: command not found'
```

See https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/676#f72520bc-0aa7-44d6-bdbf-ceabb76715d1

We have disabled the project in our downstream testing until this issue is resolved. Thank you very much!

**Comment by meteorcloudy** [comment]
/cc @xingao267 @nlopezgi
Can you add `--action_env=PATH` in the bazelci config file?

**Comment by nlopezgi** [comment]
@buchgr this should be fixed, can you please re-enable in upstream and let me know if you see issues.

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/1#_
@nlopezgi Looks like it's still failing on macos, can you look into it?

**Comment by mhlopko** [comment]
Looking at https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/8 looks like this is properly fixed. Will reenable rules_docker now. Thanks!
